# Generated by Django 5.0.6 on 2024-06-05 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_app', '0002_cart_cart_session_id_alter_cart_user_order_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vending_app.user'),
        ),
    ]
