# Generated by Django 5.0.6 on 2024-06-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_app', '0004_alter_receipt_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'get_latest_by': 'receipt_datetime'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
